// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: segmenter.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#ifndef GRPC_segmenter_2eproto__INCLUDED
#define GRPC_segmenter_2eproto__INCLUDED

#include "segmenter.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace segmenter {

// The TaskManager service definition.
class TaskManager GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status StartTask(::grpc::ClientContext* context, const ::segmenter::TaskConfig& request, ::segmenter::StartTaskReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::StartTaskReply>> AsyncStartTask(::grpc::ClientContext* context, const ::segmenter::TaskConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::StartTaskReply>>(AsyncStartTaskRaw(context, request, cq));
    }
    virtual ::grpc::Status StopTask(::grpc::ClientContext* context, const ::segmenter::TaskId& request, ::segmenter::StopTaskReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::StopTaskReply>> AsyncStopTask(::grpc::ClientContext* context, const ::segmenter::TaskId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::StopTaskReply>>(AsyncStopTaskRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPlayList(::grpc::ClientContext* context, const ::segmenter::GetPlayListConfig& request, ::segmenter::GetPlayListReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::GetPlayListReply>> AsyncGetPlayList(::grpc::ClientContext* context, const ::segmenter::GetPlayListConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::GetPlayListReply>>(AsyncGetPlayListRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::StartTaskReply>* AsyncStartTaskRaw(::grpc::ClientContext* context, const ::segmenter::TaskConfig& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::StopTaskReply>* AsyncStopTaskRaw(::grpc::ClientContext* context, const ::segmenter::TaskId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::segmenter::GetPlayListReply>* AsyncGetPlayListRaw(::grpc::ClientContext* context, const ::segmenter::GetPlayListConfig& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status StartTask(::grpc::ClientContext* context, const ::segmenter::TaskConfig& request, ::segmenter::StartTaskReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::segmenter::StartTaskReply>> AsyncStartTask(::grpc::ClientContext* context, const ::segmenter::TaskConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::segmenter::StartTaskReply>>(AsyncStartTaskRaw(context, request, cq));
    }
    ::grpc::Status StopTask(::grpc::ClientContext* context, const ::segmenter::TaskId& request, ::segmenter::StopTaskReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::segmenter::StopTaskReply>> AsyncStopTask(::grpc::ClientContext* context, const ::segmenter::TaskId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::segmenter::StopTaskReply>>(AsyncStopTaskRaw(context, request, cq));
    }
    ::grpc::Status GetPlayList(::grpc::ClientContext* context, const ::segmenter::GetPlayListConfig& request, ::segmenter::GetPlayListReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::segmenter::GetPlayListReply>> AsyncGetPlayList(::grpc::ClientContext* context, const ::segmenter::GetPlayListConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::segmenter::GetPlayListReply>>(AsyncGetPlayListRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::segmenter::StartTaskReply>* AsyncStartTaskRaw(::grpc::ClientContext* context, const ::segmenter::TaskConfig& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::segmenter::StopTaskReply>* AsyncStopTaskRaw(::grpc::ClientContext* context, const ::segmenter::TaskId& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::segmenter::GetPlayListReply>* AsyncGetPlayListRaw(::grpc::ClientContext* context, const ::segmenter::GetPlayListConfig& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_StartTask_;
    const ::grpc::RpcMethod rpcmethod_StopTask_;
    const ::grpc::RpcMethod rpcmethod_GetPlayList_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StartTask(::grpc::ServerContext* context, const ::segmenter::TaskConfig* request, ::segmenter::StartTaskReply* response);
    virtual ::grpc::Status StopTask(::grpc::ServerContext* context, const ::segmenter::TaskId* request, ::segmenter::StopTaskReply* response);
    virtual ::grpc::Status GetPlayList(::grpc::ServerContext* context, const ::segmenter::GetPlayListConfig* request, ::segmenter::GetPlayListReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_StartTask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartTask() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTask(::grpc::ServerContext* context, const ::segmenter::TaskConfig* request, ::segmenter::StartTaskReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTask(::grpc::ServerContext* context, ::segmenter::TaskConfig* request, ::grpc::ServerAsyncResponseWriter< ::segmenter::StartTaskReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_StopTask() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StopTask() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTask(::grpc::ServerContext* context, const ::segmenter::TaskId* request, ::segmenter::StopTaskReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopTask(::grpc::ServerContext* context, ::segmenter::TaskId* request, ::grpc::ServerAsyncResponseWriter< ::segmenter::StopTaskReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPlayList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetPlayList() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetPlayList() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayList(::grpc::ServerContext* context, const ::segmenter::GetPlayListConfig* request, ::segmenter::GetPlayListReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlayList(::grpc::ServerContext* context, ::segmenter::GetPlayListConfig* request, ::grpc::ServerAsyncResponseWriter< ::segmenter::GetPlayListReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartTask<WithAsyncMethod_StopTask<WithAsyncMethod_GetPlayList<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_StartTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_StartTask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartTask() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTask(::grpc::ServerContext* context, const ::segmenter::TaskConfig* request, ::segmenter::StartTaskReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_StopTask() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StopTask() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTask(::grpc::ServerContext* context, const ::segmenter::TaskId* request, ::segmenter::StopTaskReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPlayList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetPlayList() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetPlayList() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayList(::grpc::ServerContext* context, const ::segmenter::GetPlayListConfig* request, ::segmenter::GetPlayListReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace segmenter


#endif  // GRPC_segmenter_2eproto__INCLUDED
